[package]
name = "artifact-api"
version = "0.1.0"
authors = ["Jackson Hong <jacksonxxhong@gmail.com>"]

[dependencies]
reqwest = "0.9.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
mockito = "0.13.0"